name: swiss_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cli_util: ^0.3.5
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
